name: "Publish"

on:
  push: 
    branches:
      - master
     

jobs:
      name: "Publish"
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name:  Node
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
              registry-url: https://registry.npmjs.org/
          - name: publish
            run: npm publish --access public
            working-directory: my-package
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}